// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * ExampleRequest
 */
export const zExampleRequest = z.object({
    name: z.string().register(z.globalRegistry, {
        description: 'The name to be processed'
    }),
    age: z.optional(z.union([
        z.int().gte(0),
        z.null()
    ]))
});

/**
 * ExampleResponse
 */
export const zExampleResponse = z.object({
    message: z.string().register(z.globalRegistry, {
        description: 'The response message'
    }),
    claims: z.object({}).register(z.globalRegistry, {
        description: 'The claims associated with the response'
    }),
    test_value: z.optional(z.union([
        z.int().gt(0),
        z.null()
    ]))
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zHttpException = z.object({
    detail: z.string()
});

export const zTestExampleEndpointData = z.object({
    body: zExampleRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zTestExampleEndpointResponse = zExampleResponse;